use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :autogrow_server, AutogrowServerWeb.Endpoint,
  url: [host: "example.com", port: 80],


# Do not print debug messages in production
config :logger, level: :info

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :autogrow_server, AutogrowServerWeb.Endpoint,
#       ...
#       url: [host: "example.com", port: 443],
#       https: [
#         port: 443,
#         cipher_suite: :strong,
#         keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#         certfile: System.get_env("SOME_APP_SSL_CERT_PATH"),
#         transport_options: [socket_opts: [:inet6]]
#       ]
#
# The `cipher_suite` is set to `:strong` to support only the
# latest and more secure SSL ciphers. This means old browsers
# and clients may not be supported. You can set it to
# `:compatible` for wider support.
#
# `:keyfile` and `:certfile` expect an absolute path to the key
# and cert in disk or a relative path inside priv, for example
# "priv/ssl/server.key". For all supported SSL configuration
# options, see https://hexdocs.pm/plug/Plug.SSL.html#configure/1
#
# We also recommend setting `force_ssl` in your endpoint, ensuring
# no data is ever sent via http, always redirecting to https:
#
#     config :autogrow_server, AutogrowServerWeb.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

secret_key_base =
  System.get_env("SECRET_KEY_BASE") ||
    "1mvwNaiG7gwIofHFoU1EIBEzYby7yEOgHvjT5yqvJ3/YclsLlzAtEIoUlR7lZQUu"

config :autogrow_server, AutogrowServerWeb.Endpoint,
  http: [port: 80],
  url: [host: "autogrow.local", port: 80],
  secret_key_base: secret_key_base,
  root: Path.dirname(__DIR__),
  server: true,
  render_errors: [view: AutogrowServerWeb.ErrorView, accepts: ~w(html json), layout: false],
  pubsub_server: AutogrowServer.PubSub,
  live_view: [signing_salt: "037tr3tR"],
  cache_static_manifest: "priv/static/cache_manifest.json",
  transport_options: [socket_opts: [:inet6]]


# Use Jason for JSON parsing in Phoenix
config :phoenix, :json_library, Jason

# ## Using releases
#
# If you are doing OTP releases, you need to instruct Phoenix
# to start each relevant endpoint:
#
#     config :autogrow_server, AutogrowServerWeb.Endpoint, server: true
#
# Then you can assemble a release by calling `mix release`.
# See `mix help release` for more information.
